#!/usr/bin/env bash
# Automatic generated, DON'T MODIFY IT.

# @flag -h --help                                  show this help message and exit
# @option --model                                  Specify the model to use for the main chat [env var: AIDER_MODEL]
# @option --openai-api-key <OPENAI_API_KEY>        Specify the OpenAI API key [env var: AIDER_OPENAI_API_KEY]
# @option --anthropic-api-key <ANTHROPIC_API_KEY>  Specify the Anthropic API key [env var: AIDER_ANTHROPIC_API_KEY]
# @option --openai-api-base <OPENAI_API_BASE>      Specify the api base url [env var: AIDER_OPENAI_API_BASE]
# @option --openai-api-type <OPENAI_API_TYPE>      (deprecated, use --set-env OPENAI_API_TYPE=<value>) [env var: AIDER_OPENAI_API_TYPE]
# @option --openai-api-version <OPENAI_API_VERSION>  (deprecated, use --set-env OPENAI_API_VERSION=<value>) [env var: AIDER_OPENAI_API_VERSION]
# @option --openai-api-deployment-id <OPENAI_API_DEPLOYMENT_ID>  (deprecated, use --set-env OPENAI_API_DEPLOYMENT_ID=<value>) [env var: AIDER_OPENAI_API_DEPLOYMENT_ID]
# @option --openai-organization-id <OPENAI_ORGANIZATION_ID>  (deprecated, use --set-env OPENAI_ORGANIZATION=<value>) [env var: AIDER_OPENAI_ORGANIZATION_ID]
# @option --set-env <ENV_VAR_NAME=value>           Set an environment variable (to control API settings, can be used multiple times) [env var: AIDER_SET_ENV]
# @option --api-key <PROVIDER=KEY>                 Set an API key for a provider (eg: --api-key provider=<key> sets PROVIDER_API_KEY=<key>) [env var: AIDER_API_KEY]
# @option --list-models <MODEL>                    List known models which match the (partial) MODEL name [env var: AIDER_LIST_MODELS]
# @option --models <MODEL>                         List known models which match the (partial) MODEL name [env var: AIDER_LIST_MODELS]
# @option --model-settings-file <MODEL_SETTINGS_FILE>  Specify a file with aider model settings for unknown models [env var: AIDER_MODEL_SETTINGS_FILE]
# @option --model-metadata-file <MODEL_METADATA_FILE>  Specify a file with context window and costs for unknown models [env var: AIDER_MODEL_METADATA_FILE]
# @option --alias <ALIAS:MODEL>                    Add a model alias (can be used multiple times) [env var: AIDER_ALIAS]
# @option --reasoning-effort <REASONING_EFFORT>    Set the reasoning_effort API parameter (default: not set) [env var: AIDER_REASONING_EFFORT]
# @option --thinking-tokens <THINKING_TOKENS>      Set the thinking token budget for models that support it.
# @flag --verify-ssl                               Verify the SSL cert when connecting to models (default: True) [env var: AIDER_VERIFY_SSL]
# @flag --no-verify-ssl                            Verify the SSL cert when connecting to models (default: True) [env var: AIDER_VERIFY_SSL]
# @option --timeout                                Timeout in seconds for API calls (default: None) [env var: AIDER_TIMEOUT]
# @option --edit-format <EDIT_FORMAT>              Specify what edit format the LLM should use (default depends on model) [env var: AIDER_EDIT_FORMAT]
# @option --chat-mode <EDIT_FORMAT>                Specify what edit format the LLM should use (default depends on model) [env var: AIDER_EDIT_FORMAT]
# @flag --architect                                Use architect edit format for the main chat [env var: AIDER_ARCHITECT]
# @flag --auto-accept-architect                    Enable/disable automatic acceptance of architect changes (default: True) [env var: AIDER_AUTO_ACCEPT_ARCHITECT]
# @flag --no-auto-accept-architect                 Enable/disable automatic acceptance of architect changes (default: True) [env var: AIDER_AUTO_ACCEPT_ARCHITECT]
# @option --weak-model <WEAK_MODEL>                Specify the model to use for commit messages and chat history summarization (default depends on --model) [env var: AIDER_WEAK_MODEL]
# @option --editor-model <EDITOR_MODEL>            Specify the model to use for editor tasks (default depends on --model) [env var: AIDER_EDITOR_MODEL]
# @option --editor-edit-format <EDITOR_EDIT_FORMAT>  Specify the edit format for the editor model (default: depends on editor model) [env var: AIDER_EDITOR_EDIT_FORMAT]
# @flag --show-model-warnings                      Only work with models that have meta-data available (default: True) [env var: AIDER_SHOW_MODEL_WARNINGS]
# @flag --no-show-model-warnings                   Only work with models that have meta-data available (default: True) [env var: AIDER_SHOW_MODEL_WARNINGS]
# @flag --check-model-accepts-settings             Check if model accepts settings like reasoning_effort/thinking_tokens (default: True) [env var: AIDER_CHECK_MODEL_ACCEPTS_SETTINGS]
# @flag --no-check-model-accepts-settings          Check if model accepts settings like reasoning_effort/thinking_tokens (default: True) [env var: AIDER_CHECK_MODEL_ACCEPTS_SETTINGS]
# @option --max-chat-history-tokens <MAX_CHAT_HISTORY_TOKENS>  Soft limit on tokens for chat history, after which summarization begins.
# @flag --cache-prompts                            Enable caching of prompts (default: False) [env var: AIDER_CACHE_PROMPTS]
# @flag --no-cache-prompts                         Enable caching of prompts (default: False) [env var: AIDER_CACHE_PROMPTS]
# @option --cache-keepalive-pings <CACHE_KEEPALIVE_PINGS>  Number of times to ping at 5min intervals to keep prompt cache warm (default: 0) [env var: AIDER_CACHE_KEEPALIVE_PINGS]
# @option --map-tokens <MAP_TOKENS>                Suggested number of tokens to use for repo map, use 0 to disable [env var: AIDER_MAP_TOKENS]
# @option --map-refresh[auto|always|files|manual]  Control how often the repo map is refreshed.
# @option --map-multiplier-no-files <MAP_MULTIPLIER_NO_FILES>  Multiplier for map tokens when no files are specified (default: 2) [env var: AIDER_MAP_MULTIPLIER_NO_FILES]
# @option --input-history-file <INPUT_HISTORY_FILE>  Specify the chat input history file (default: /home/skogix/.local/src/argc-completions/.aider.input.history) [env var: AIDER_INPUT_HISTORY_FILE]
# @option --chat-history-file <CHAT_HISTORY_FILE>  Specify the chat history file (default: /home/skogix/.local/src/argc-completions/.aider.chat.history.md) [env var: AIDER_CHAT_HISTORY_FILE]
# @flag --restore-chat-history                     Restore the previous chat history messages (default: False) [env var: AIDER_RESTORE_CHAT_HISTORY]
# @flag --no-restore-chat-history                  Restore the previous chat history messages (default: False) [env var: AIDER_RESTORE_CHAT_HISTORY]
# @option --llm-history-file <LLM_HISTORY_FILE>    Log the conversation with the LLM to this file (for example, .aider.llm.history) [env var: AIDER_LLM_HISTORY_FILE]
# @flag --dark-mode                                Use colors suitable for a dark terminal background (default: False) [env var: AIDER_DARK_MODE]
# @flag --light-mode                               Use colors suitable for a light terminal background (default: False) [env var: AIDER_LIGHT_MODE]
# @flag --pretty                                   Enable/disable pretty, colorized output (default: True) [env var: AIDER_PRETTY]
# @flag --no-pretty                                Enable/disable pretty, colorized output (default: True) [env var: AIDER_PRETTY]
# @flag --stream                                   Enable/disable streaming responses (default: True) [env var: AIDER_STREAM]
# @flag --no-stream                                Enable/disable streaming responses (default: True) [env var: AIDER_STREAM]
# @option --user-input-color <USER_INPUT_COLOR>    Set the color for user input (default: ♯00cc00) [env var: AIDER_USER_INPUT_COLOR]
# @option --tool-output-color <TOOL_OUTPUT_COLOR>  Set the color for tool output (default: None) [env var: AIDER_TOOL_OUTPUT_COLOR]
# @option --tool-error-color <TOOL_ERROR_COLOR>    Set the color for tool error messages (default: ♯FF2222) [env var: AIDER_TOOL_ERROR_COLOR]
# @option --tool-warning-color <TOOL_WARNING_COLOR>  Set the color for tool warning messages (default: ♯FFA500) [env var: AIDER_TOOL_WARNING_COLOR]
# @option --assistant-output-color <ASSISTANT_OUTPUT_COLOR>  Set the color for assistant output (default: ♯0088ff) [env var: AIDER_ASSISTANT_OUTPUT_COLOR]
# @option --completion-menu-color <COLOR>          Set the color for the completion menu (default: terminal's default text color) [env var: AIDER_COMPLETION_MENU_COLOR]
# @option --completion-menu-bg-color <COLOR>       Set the background color for the completion menu (default: terminal's default background color) [env var: AIDER_COMPLETION_MENU_BG_COLOR]
# @option --completion-menu-current-color <COLOR>  Set the color for the current item in the completion menu (default: terminal's default background color) [env var: AIDER_COMPLETION_MENU_CURRENT_COLOR]
# @option --completion-menu-current-bg-color <COLOR>  Set the background color for the current item in the completion menu (default: terminal's default text color) [env var: AIDER_COMPLETION_MENU_CURRENT_BG_COLOR]
# @option --code-theme <CODE_THEME>                Set the markdown code theme (default: default, other options include monokai, solarized-dark, solarized-light, or a Pygments builtin style, see
# @flag --show-diffs                               Show diffs when committing changes (default: False) [env var: AIDER_SHOW_DIFFS]
# @flag --git                                      Enable/disable looking for a git repo (default: True) [env var: AIDER_GIT]
# @flag --no-git                                   Enable/disable looking for a git repo (default: True) [env var: AIDER_GIT]
# @flag --gitignore                                Enable/disable adding .aider* to .gitignore (default: True) [env var: AIDER_GITIGNORE]
# @flag --no-gitignore                             Enable/disable adding .aider* to .gitignore (default: True) [env var: AIDER_GITIGNORE]
# @flag --add-gitignore-files                      Enable/disable the addition of files listed in .gitignore to Aider's editing scope.
# @flag --no-add-gitignore-files                   Enable/disable the addition of files listed in .gitignore to Aider's editing scope.
# @option --aiderignore                            Specify the aider ignore file (default: .aiderignore in git root) [env var: AIDER_AIDERIGNORE]
# @flag --subtree-only                             Only consider files in the current subtree of the git repository [env var: AIDER_SUBTREE_ONLY]
# @flag --auto-commits                             Enable/disable auto commit of LLM changes (default: True) [env var: AIDER_AUTO_COMMITS]
# @flag --no-auto-commits                          Enable/disable auto commit of LLM changes (default: True) [env var: AIDER_AUTO_COMMITS]
# @flag --dirty-commits                            Enable/disable commits when repo is found dirty (default: True) [env var: AIDER_DIRTY_COMMITS]
# @flag --no-dirty-commits                         Enable/disable commits when repo is found dirty (default: True) [env var: AIDER_DIRTY_COMMITS]
# @flag --attribute-author                         Attribute aider code changes in the git author name (default: True).
# @flag --no-attribute-author                      Attribute aider code changes in the git author name (default: True).
# @flag --attribute-committer                      Attribute aider commits in the git committer name (default: True).
# @flag --no-attribute-committer                   Attribute aider commits in the git committer name (default: True).
# @flag --attribute-commit-message-author          Prefix commit messages with 'aider: ' if aider authored the changes (default: False) [env var: AIDER_ATTRIBUTE_COMMIT_MESSAGE_AUTHOR]
# @flag --no-attribute-commit-message-author       Prefix commit messages with 'aider: ' if aider authored the changes (default: False) [env var: AIDER_ATTRIBUTE_COMMIT_MESSAGE_AUTHOR]
# @flag --attribute-commit-message-committer       Prefix all commit messages with 'aider: ' (default: False) [env var: AIDER_ATTRIBUTE_COMMIT_MESSAGE_COMMITTER]
# @flag --no-attribute-commit-message-committer    Prefix all commit messages with 'aider: ' (default: False) [env var: AIDER_ATTRIBUTE_COMMIT_MESSAGE_COMMITTER]
# @flag --attribute-co-authored-by                 Attribute aider edits using the Co-authored-by trailer in the commit message (default: True).
# @flag --no-attribute-co-authored-by              Attribute aider edits using the Co-authored-by trailer in the commit message (default: True).
# @flag --git-commit-verify                        Enable/disable git pre-commit hooks with --no-verify (default: False) [env var: AIDER_GIT_COMMIT_VERIFY]
# @flag --no-git-commit-verify                     Enable/disable git pre-commit hooks with --no-verify (default: False) [env var: AIDER_GIT_COMMIT_VERIFY]
# @flag --commit                                   Commit all pending changes with a suitable commit message, then exit [env var: AIDER_COMMIT]
# @option --commit-prompt <PROMPT>                 Specify a custom prompt for generating commit messages [env var: AIDER_COMMIT_PROMPT]
# @flag --dry-run                                  Perform a dry run without modifying files (default: False) [env var: AIDER_DRY_RUN]
# @flag --no-dry-run                               Perform a dry run without modifying files (default: False) [env var: AIDER_DRY_RUN]
# @flag --skip-sanity-check-repo                   Skip the sanity check for the git repository (default: False) [env var: AIDER_SKIP_SANITY_CHECK_REPO]
# @flag --watch-files                              Enable/disable watching files for ai coding comments (default: False) [env var: AIDER_WATCH_FILES]
# @flag --no-watch-files                           Enable/disable watching files for ai coding comments (default: False) [env var: AIDER_WATCH_FILES]
# @flag --lint                                     Lint and fix provided files, or dirty files if none provided [env var: AIDER_LINT]
# @option --lint-cmd <LINT_CMD>                    Specify lint commands to run for different languages, eg: "python: flake8 --select=..." (can be used multiple times) [env var: AIDER_LINT_CMD]
# @flag --auto-lint                                Enable/disable automatic linting after changes (default: True) [env var: AIDER_AUTO_LINT]
# @flag --no-auto-lint                             Enable/disable automatic linting after changes (default: True) [env var: AIDER_AUTO_LINT]
# @option --test-cmd <TEST_CMD>                    Specify command to run tests [env var: AIDER_TEST_CMD]
# @flag --auto-test                                Enable/disable automatic testing after changes (default: False) [env var: AIDER_AUTO_TEST]
# @flag --no-auto-test                             Enable/disable automatic testing after changes (default: False) [env var: AIDER_AUTO_TEST]
# @flag --test                                     Run tests, fix problems found and then exit [env var: AIDER_TEST]
# @flag --analytics                                Enable/disable analytics for current session (default: random) [env var: AIDER_ANALYTICS]
# @flag --no-analytics                             Enable/disable analytics for current session (default: random) [env var: AIDER_ANALYTICS]
# @option --analytics-log <ANALYTICS_LOG_FILE>     Specify a file to log analytics events [env var: AIDER_ANALYTICS_LOG]
# @flag --analytics-disable                        Permanently disable analytics [env var: AIDER_ANALYTICS_DISABLE]
# @option --analytics-posthog-host <ANALYTICS_POSTHOG_HOST>  Send analytics to custom PostHog instance [env var: AIDER_ANALYTICS_POSTHOG_HOST]
# @option --analytics-posthog-project-api-key <ANALYTICS_POSTHOG_PROJECT_API_KEY>  Send analytics to custom PostHog project [env var: AIDER_ANALYTICS_POSTHOG_PROJECT_API_KEY]
# @flag --just-check-update                        Check for updates and return status in the exit code [env var: AIDER_JUST_CHECK_UPDATE]
# @flag --check-update                             Check for new aider versions on launch [env var: AIDER_CHECK_UPDATE]
# @flag --no-check-update                          Check for new aider versions on launch [env var: AIDER_CHECK_UPDATE]
# @flag --show-release-notes                       Show release notes on first run of new version (default: None, ask user) [env var: AIDER_SHOW_RELEASE_NOTES]
# @flag --no-show-release-notes                    Show release notes on first run of new version (default: None, ask user) [env var: AIDER_SHOW_RELEASE_NOTES]
# @flag --install-main-branch                      Install the latest version from the main branch [env var: AIDER_INSTALL_MAIN_BRANCH]
# @flag --upgrade                                  Upgrade aider to the latest version from PyPI [env var: AIDER_UPGRADE]
# @flag --update                                   Upgrade aider to the latest version from PyPI [env var: AIDER_UPGRADE]
# @flag --version                                  Show the version number and exit
# @option -m <COMMAND>                             Specify a single message to send the LLM, process reply then exit (disables chat mode) [env var: AIDER_MESSAGE]
# @option --message <COMMAND>                      Specify a single message to send the LLM, process reply then exit (disables chat mode) [env var: AIDER_MESSAGE]
# @option --msg <COMMAND>                          Specify a single message to send the LLM, process reply then exit (disables chat mode) [env var: AIDER_MESSAGE]
# @option -f --message-file <MESSAGE_FILE>         Specify a file containing the message to send the LLM, process reply, then exit (disables chat mode) [env var: AIDER_MESSAGE_FILE]
# @flag --gui                                      Run aider in your browser (default: False) [env var: AIDER_GUI]
# @flag --no-gui                                   Run aider in your browser (default: False) [env var: AIDER_GUI]
# @flag --browser                                  Run aider in your browser (default: False) [env var: AIDER_GUI]
# @flag --no-browser                               Run aider in your browser (default: False) [env var: AIDER_GUI]
# @flag --copy-paste                               Enable automatic copy/paste of chat between aider and web UI (default: False) [env var: AIDER_COPY_PASTE]
# @flag --no-copy-paste                            Enable automatic copy/paste of chat between aider and web UI (default: False) [env var: AIDER_COPY_PASTE]
# @option --apply <FILE>                           Apply the changes from the given file instead of running the chat (debug) [env var: AIDER_APPLY]
# @flag --apply-clipboard-edits                    Apply clipboard contents as edits using the main model's editor format [env var: AIDER_APPLY_CLIPBOARD_EDITS]
# @flag --exit                                     Do all startup activities then exit before accepting user input (debug) [env var: AIDER_EXIT]
# @flag --show-repo-map                            Print the repo map and exit (debug) [env var: AIDER_SHOW_REPO_MAP]
# @flag --show-prompts                             Print the system prompts and exit (debug) [env var: AIDER_SHOW_PROMPTS]
# @option --voice-format <VOICE_FORMAT>            Audio format for voice recording (default: wav).
# @option --voice-language <VOICE_LANGUAGE>        Specify the language for voice using ISO 639-1 code (default: auto) [env var: AIDER_VOICE_LANGUAGE]
# @option --voice-input-device <VOICE_INPUT_DEVICE>  Specify the input device name for voice recording [env var: AIDER_VOICE_INPUT_DEVICE]
# @flag --disable-playwright                       Never prompt for or attempt to install Playwright for web scraping (default: False).
# @option --file                                   specify a file to edit (can be used multiple times) [env var: AIDER_FILE]
# @option --read <FILE>                            specify a read-only file (can be used multiple times) [env var: AIDER_READ]
# @flag --vim                                      Use VI editing mode in the terminal (default: False) [env var: AIDER_VIM]
# @option --chat-language <CHAT_LANGUAGE>          Specify the language to use in the chat (default: None, uses system settings) [env var: AIDER_CHAT_LANGUAGE]
# @option --commit-language <COMMIT_LANGUAGE>      Specify the language to use in the commit message (default: None, user language) [env var: AIDER_COMMIT_LANGUAGE]
# @flag --yes-always                               Always say yes to every confirmation [env var: AIDER_YES_ALWAYS]
# @flag -v --verbose                               Enable verbose output [env var: AIDER_VERBOSE]
# @option --load <LOAD_FILE>                       Load and execute /commands from a file on launch [env var: AIDER_LOAD]
# @option --encoding                               Specify the encoding for input and output (default: utf-8) [env var: AIDER_ENCODING]
# @option --line-endings[platform|lf|crlf]         Line endings to use when writing files (default: platform) [env var: AIDER_LINE_ENDINGS]
# @option -c --config <CONFIG_FILE>                Specify the config file (default: search for .aider.conf.yml in git root, cwd or home directory)
# @option --env-file <ENV_FILE>                    Specify the .env file to load (default: .env in git root) [env var: AIDER_ENV_FILE]
# @flag --suggest-shell-commands                   Enable/disable suggesting shell commands (default: True) [env var: AIDER_SUGGEST_SHELL_COMMANDS]
# @flag --no-suggest-shell-commands                Enable/disable suggesting shell commands (default: True) [env var: AIDER_SUGGEST_SHELL_COMMANDS]
# @flag --fancy-input                              Enable/disable fancy input with history and completion (default: True) [env var: AIDER_FANCY_INPUT]
# @flag --no-fancy-input                           Enable/disable fancy input with history and completion (default: True) [env var: AIDER_FANCY_INPUT]
# @flag --multiline                                Enable/disable multi-line input mode with Meta-Enter to submit (default: False) [env var: AIDER_MULTILINE]
# @flag --no-multiline                             Enable/disable multi-line input mode with Meta-Enter to submit (default: False) [env var: AIDER_MULTILINE]
# @flag --notifications                            Enable/disable terminal bell notifications when LLM responses are ready (default: False) [env var: AIDER_NOTIFICATIONS]
# @flag --no-notifications                         Enable/disable terminal bell notifications when LLM responses are ready (default: False) [env var: AIDER_NOTIFICATIONS]
# @option --notifications-command <COMMAND>        Specify a command to run for notifications instead of the terminal bell.
# @flag --detect-urls                              Enable/disable detection and offering to add URLs to chat (default: True) [env var: AIDER_DETECT_URLS]
# @flag --no-detect-urls                           Enable/disable detection and offering to add URLs to chat (default: True) [env var: AIDER_DETECT_URLS]
# @option --editor                                 Specify which editor to use for the /editor command [env var: AIDER_EDITOR]
# @option --shell-completions[bash|tcsh|zsh] <SHELL>  Print shell completion script for the specified SHELL and exit.
# @flag --opus                                     Use claude-3-opus-20240229 model for the main chat (deprecated, use --model) [env var: AIDER_OPUS]
# @flag --sonnet                                   Use anthropic/claude-3-7-sonnet-20250219 model for the main chat (deprecated, use --model) [env var: AIDER_SONNET]
# @flag --haiku                                    Use claude-3-5-haiku-20241022 model for the main chat (deprecated, use --model) [env var: AIDER_HAIKU]
# @flag -4 --4                                     Use gpt-4-0613 model for the main chat (deprecated, use --model) [env var: AIDER_4]
# @flag --4o                                       Use gpt-4o model for the main chat (deprecated, use --model) [env var: AIDER_4O]
# @flag --mini                                     Use gpt-4o-mini model for the main chat (deprecated, use --model) [env var: AIDER_MINI]
# @flag --4-turbo                                  Use gpt-4-1106-preview model for the main chat (deprecated, use --model) [env var: AIDER_4_TURBO]
# @flag -3                                         Use gpt-3.5-turbo model for the main chat (deprecated, use --model) [env var: AIDER_35TURBO]
# @flag --35turbo                                  Use gpt-3.5-turbo model for the main chat (deprecated, use --model) [env var: AIDER_35TURBO]
# @flag --35-turbo                                 Use gpt-3.5-turbo model for the main chat (deprecated, use --model) [env var: AIDER_35TURBO]
# @flag --3                                        Use gpt-3.5-turbo model for the main chat (deprecated, use --model) [env var: AIDER_35TURBO]
# @flag --deepseek                                 Use deepseek/deepseek-chat model for the main chat (deprecated, use --model) [env var: AIDER_DEEPSEEK]
# @flag --o1-mini                                  Use o1-mini model for the main chat (deprecated, use --model) [env var: AIDER_O1_MINI]
# @flag --o1-preview                               Use o1-preview model for the main chat (deprecated, use --model) [env var: AIDER_O1_PREVIEW]
# @arg file*

command eval "$(argc --argc-eval "$0" "$@")"