.TH FFMPEG 1  "ffmpeg 0.0.0" 
.SH NAME
ffmpeg
.SH SYNOPSIS
\fBffmpeg\fR [OPTIONS] [OUTFILE]...
.SH OPTIONS
.TP
\fB\-L\fR
.br
show license
.TP
\fB\-h\fR=\fITOPIC\fR
.br
show help
.TP
\fB\-version\fR
.br
show version
.TP
\fB\-muxers\fR
.br
show available muxers
.TP
\fB\-demuxers\fR
.br
show available demuxers
.TP
\fB\-devices\fR
.br
show available devices
.TP
\fB\-decoders\fR
.br
show available decoders
.TP
\fB\-encoders\fR
.br
show available encoders
.TP
\fB\-filters\fR
.br
show available filters
.TP
\fB\-pix_fmts\fR
.br
show available pixel formats
.TP
\fB\-layouts\fR
.br
show standard channel layouts
.TP
\fB\-sample_fmts\fR
.br
show available audio sample formats
.TP
\fB\-v\fR=\fILOGLEVEL\fR
.br
set logging level
.TP
\fB\-y\fR
.br
overwrite output files
.TP
\fB\-n\fR
.br
never overwrite output files
.TP
\fB\-print_graphs\fR
.br
print execution graph data to stderr
.TP
\fB\-print_graphs_file\fR=\fIFILENAME\fR
.br
write execution graph data to the specified file
.TP
\fB\-print_graphs_format\fR=\fIFORMAT\fR
.br
set the output printing format
.br

.br
[\fIpossible values: \fRdefault, compact, csv, flat, ini, json, xml, mermaid, mermaidhtml]
.TP
\fB\-stats\fR
.br
print progress report during encoding
.TP
\fB\-f\fR=\fIFMT\fR
.br
force container format (auto\-detected otherwise)
.TP
\fB\-t\fR=\fIDURATION\fR
.br
stop transcoding after specified duration
.TP
\fB\-to\fR=\fITIME\-STOP\fR
.br
stop transcoding after specified time is reached
.TP
\fB\-ss\fR=\fITIME\-OFF\fR
.br
start transcoding at specified time
.TP
\fB\-metadata\fR \fI:<SPEC>\fR \fIKEY=VALUE\fR
.br
add metadata
.TP
\fB\-c\fR \fI:<STREAM\-SPEC>\fR \fICODEC\fR
.br
select encoder/decoder ('copy' to copy stream without reencoding)
.TP
\fB\-filter\fR \fI:<STREAM\-SPEC>\fR \fIFILTER\-GRAPH\fR
.br
apply specified filters to audio/video
.TP
\fB\-r\fR \fI:<STREAM\-SPEC>\fR \fIRATE\fR
.br
override input framerate/convert to given output framerate (Hz value, fraction or abbreviation)
.TP
\fB\-aspect\fR \fI:<STREAM\-SPEC>\fR \fIASPECT\fR
.br
set aspect ratio (4:3, 16:9 or 1.3333, 1.7777)
.TP
\fB\-vn\fR
.br
disable video
.TP
\fB\-vcodec\fR=\fICODEC\fR
.br
alias for \-c:v (select encoder/decoder for video streams)
.TP
\fB\-vf\fR=[\fIFILTER\-GRAPH\fR]...
.br
alias for \-filter:v (apply filters to video streams)
.TP
\fB\-b\fR=\fIBITRATE\fR
.br
video bitrate (please use \-b:v)
.TP
\fB\-aq\fR=\fIQUALITY\fR
.br
set audio quality (codec\-specific)
.TP
\fB\-ar\fR \fI:<STREAM\-SPEC>\fR \fIRATE\fR
.br
set audio sampling rate (in Hz)
.br

.br
[\fIpossible values: \fR22050, 44100, 48000]
.TP
\fB\-ac\fR \fI:<STREAM\-SPEC>\fR \fICHANNELS\fR
.br
set number of audio channels
.TP
\fB\-an\fR
.br
disable audio
.TP
\fB\-acodec\fR=\fICODEC\fR
.br
alias for \-c:a (select encoder/decoder for audio streams)
.TP
\fB\-ab\fR=\fIBITRATE\fR
.br
alias for \-b:a (select bitrate for audio streams)
.br

.br
[\fIpossible values: \fR16, 32, 64, 128, 192, 256, 320]
.TP
\fB\-af\fR=[\fIFILTER\-GRAPH\fR]...
.br
alias for \-filter:a (apply filters to audio streams)
.TP
\fB\-sn\fR
.br
disable subtitle
.TP
\fB\-scodec\fR=\fICODEC\fR
.br
alias for \-c:s (select encoder/decoder for subtitle streams)
.TP
\fB\-help\fR
.br
Print help
.TP
[\fIOUTFILE\fR]...

